[build]
  command = "rm -rf .next && npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL,GEMINI_API_KEY,GROQ_API_KEY,SUPABASE_SERVICE_ROLE_KEY"

[functions]
  included_files = ["node_modules/@jimp/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
