[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".netlify/.next/cache"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
